export const connectionsDefaultColor = 'rgba(255, 255, 255, 0.2)'
export const connectionsGreenColor = '#4CD964'
export const connectionsBlueColor = '#007AFF'
export const connectionsOrangeColor = '#FF9500'

export const defaultIconColor = '#FFFFFF'
export const sliderIconColor = 'rgba(0, 0, 0, 0.3)'
export const selectedOrientationLockColor = '#FE6064'
export const selectedNightModeColor = '#695DDB'
export const selectedFlashLightColor = '#007AFF'